;; Keep the home directory clean.
(setq ido-save-directory-list-file
      (convert-standard-filename
       (concat user-emacs-directory "ido.last")))

;; Use flexible string matching with `ido-mode'.
(setq ido-enable-flex-matching t)

;; Always put . as the first item in file name lists; this allows the
;; current directory to be opened immediately with `dired'.
(setq ido-show-dot-for-dired t)

;; Show a file/buffer in selected window, even if that file/buffer is
;; visible in another frame.
(setq ido-default-file-method   'selected-window
      ido-default-buffer-method 'selected-window)

;; Enable `ido-mode'.
(ido-mode 1)

;; Enable `ido-everywhere'.
(ido-everywhere 1)

;; When I am opening a file (with `find-file' or `ido-find-file'), do
;; not suggest files generated by various programs.
(setq completion-ignored-extensions
      (nconc (list
              ;; Files generated by GHC
              ".hi"
              ;; Files generated by MIT Scheme
              ".bci" ".bin" ".com"
              ;; Files generated by LaTeX and friends
              ".dvi" ".pdf" ".ps"
              )
             completion-ignored-extensions))

;; Don't automatically merge work directories during file name input.
;; Use `M-s' to force the merge when it appears appropriate.
(setq ido-auto-merge-work-directories-length -1)

(provide 'preamble-ido)
